
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: billing_api_dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - cloudflared
    depends_on: []

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: billing_worker_dev
    command: python app/worker/run.py
    volumes:
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt
    env_file:
      - .env
    networks:
      - cloudflared
    depends_on: []

networks:
  cloudflare_net:
    external: true