
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bayarinternet_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - cloudflared

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bayarinternet_worker
    command: python app/worker/run.py
    restart: always
    env_file:
      - .env
    networks:
      - cloudflared

networks:
  cloudflared:
    external: true